spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://116.85.32.90:3306/springboot_shiro
    hikari:
      username: root
      password: 123456
  redis:
    database: 1
    host: 116.85.32.90
    port: 6379
    timeout: 6000
    password: password
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
server:
  port: 8081
