spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_shiro
    hikari:
      username: root
      password: 123
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 6000
    password:
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
